### PR TITLE
Mostly maintenance & revised summary function

### PR DESCRIPTION
**Pull request by hneth**
A bunch of minor commits — mostly checking, unifying, describing and documenting supporting materials (documentation and vignettes).  

Will turn to more functional fixes next...

### CODE REVIEW

**Comment by hneth** [comment]
As later commits are automatically added to open pull requests, some more functional changes follow here:

**Comment by hneth** [comment]
Please review and approve, so that I can continue fixing the next issues...  Thanks!

**Review by ndphillips — APPROVED** [review]
looks good to me, thanks!

**Comment by ndphillips** [comment]
> 

I'm sure there must be a way to create separate branches and create multiple pull requests - can you try creating feature branches? The smaller the next PRs are the faster I can review them!

Again in this one there were too many changes (almost 3,000 lines) for me to review each line. `devtools::check()` looked ok so I approved.

**Comment by hneth** [comment]
Thanks & cheers!

**Pull request merged**
